name: 'Validate JSON'
description: 'GitHub Action: Validate JSON'
author: 'Or Rosenblatt'
inputs:
  schema:
    description: 'A relative file path under the repository or a URL of a JSON schema file to validate the other JSON files with.'
    required: false
  jsons:
    description: 'One or more relative file paths under the repository of the JSON files to validate with the schema provided.'
    required: true
  separator:
    description: 'The separator that is used on `jsons` to separate each file.'
    required: false
    default: '\n'
outputs:
  invalid:
    description: 'One or more of relative file paths of the invalid JSON files, found in the repository (seperated by newline).'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding: 
  icon: 'check'
  color: purple
