on: 
  push:
    branches:
      - master

name: Compile Action

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x 
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-      
      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run pack
        
      - name: Generate token 
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Compile Action
          author_name: scratchaddons-bot[bot]
          author_email: 73682299+scratchaddons-bot[bot]@users.noreply.github.com
          add: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
